[project]
name = "calypso_go"
version = "1.0.0"
dependencies = [
    "pywebview",
    "pycairo",
    "PyGObject",
    "pylint",
    "mypy",
    "autopep8",
    "jsmin",
    "screeninfo"
]

[tool.setuptools]
py-modules = ["calypso_go"]